name: simple_benchmark_lean
num_files: 2
language: LEAN
few_shot_data_path_for_retrieval: 
few_shot_metadata_filename_for_retrieval: 
dfs_data_path_for_retrieval: 
dfs_metadata_filename_for_retrieval: 
datasets:
  - project: data/test/lean_proj
    files:
      - path: src/simple.lean
        theorems: "*"