name: compcert_test
num_files: 11
language: COQ
few_shot_data_path_for_retrieval: 
few_shot_metadata_filename_for_retrieval: 
dfs_data_path_for_retrieval: 
dfs_metadata_filename_for_retrieval: 
timeout_per_theorem_in_secs: 720
setup_cmds:
  - opam env --switch=CompCert --set-switch
datasets:
  - project: <user>/data/repos/CompCert
    files:
      - path: backend/Locations.v
        theorems: "*"
      - path: backend/RTL.v
        theorems: "*"
      - path: backend/Selectionproof.v
        theorems: "*"
      - path: cfrontend/Cop.v
        theorems: "*"
      - path: exportclight/Clightdefs.v
        theorems: "*"
      - path: MenhirLib/Validator_complete.v
        theorems: "*"
      - path: x86/SelectOpproof.v
        theorems: "*"
      - path: flocq/Calc/Round.v
        theorems: "*"
      - path: flocq/Prop/Mult_error.v
        theorems: "*"
      - path: flocq/Core/Zaux.v
        theorems: "*"
      - path: lib/Parmov.v
        theorems: "*"
      - path: lib/Wfsimpl.v
        theorems: "*"
      - path: common/Globalenvs.v
        theorems: "*"