defaults:
  - model_settings: llama2_7b_quantized_1024 # Name of model settings file
  - training_data_settings: simple_benchmark_training # Name of training data settings file
  - training_settings: basic_quantized_llama2_split_09_01 # Name of training settings file
  - override hydra/job_logging: 'disabled'

name: thrall-Llama-2-7b-hf-simple-1024-001-001 # Can be any name will be used in logs
experiment_type: 'Training' # Can be 'Training' or 'Inferencing'