name: mathcomp_test
num_files: 2
language: COQ
few_shot_data_path_for_retrieval: 
few_shot_metadata_filename_for_retrieval: 
dfs_data_path_for_retrieval: 
dfs_metadata_filename_for_retrieval: 
timeout_per_theorem_in_secs: 720
setup_cmds:
  - opam env --switch=MathComp --set-switch
datasets:
  - project: <root>/data/repos/math-comp
    files:
      - path: mathcomp/algebra/mxalgebra.v
        theorems:
          - ltmxE
          - ltmxW
          - ltmxEneq
          - submxElt
          - mxrankE
          - rank_leq_row
          - row_leq_rank
          - rank_leq_col
          - col_leq_rank
          - eq_row_full
          - row_ebase_unit
          - col_ebase_unit
          - mulmx_ebase
          - mulmx_base
          - mulmx1_min_rank
          - mulmx_max_rank
          - mxrank_tr
          - mxrank_add
          - mxrankM_maxl
          - mxrankM_maxr
          - mxrank_scale
          - mxrank_scale_nz
          - mxrank_opp
          - mxrank0
          - mxrank_eq0
          - mulmx_coker
          - submxE
          - mulmxKpV
          - mulmxVp
          - mulmxKp
          - submxP
          - submx_refl
          - submxMl
          - submxMr
          - mulmx_sub
          - submx_trans
          - ltmx_sub_trans
          - sub_ltmx_trans
          - ltmx_trans
          - ltmx_irrefl
          - sub0mx
          - submx0null
          - submx0
          - lt0mx
          - ltmx0
          - eqmx0P
          - eqmx_eq0
          - addmx_sub
          - rowsub_sub
          - summx_sub
          - scalemx_sub
          - row_sub
          - eq_row_sub
          - nz_row_sub
          - row_subP
          - rV_subP
          - row_subPn
          - sub_rVP
          - rank_rV
          - rowV0Pn
          - rowV0P
          - submx_full
          - row_fullP
          - row_full_inj
          - row_freeP
          - row_free_inj
          - row_free_unit
          - row_full_unit
          - mxrank_unit
          - mxrank1
          - mxrank_delta
          - mxrankS
          - submx1
          - sub1mx
          - ltmx1
          - lt1mx
          - pinvmxE
          - mulVpmx
          - pinvmx_free
          - pinvmx_full
          - eqmxP
          - rV_eqP
          - mulmxP
          - eqmx_refl
          - eqmx_sym
          - eqmx_trans
          - eqmx_rank
          - lt_eqmx
          - eqmxMr
          - eqmxMfull
          - eqmx0
          - eqmx_scale
          - eqmx_opp
          - submxMfree
          - eqmxMfree
          - mxrankMfree
          - eq_row_base
          - row_base0
          - qidmx_eq1
          - genmx_witnessP
          - genmxE
          - eq_genmx
          - genmxP
          - genmx0
          - genmx1
          - genmx_id
          - row_base_free
          - mxrank_gen
          - col_base_full
          - mxrank_leqif_sup
          - mxrank_leqif_eq
          - ltmxErank
          - rank_ltmx
          - eqmx_cast
          - row_full_castmx
          - row_free_castmx
          - eqmx_conform
          - eqmx_sum_nop
          - rowsub_comp_sub
          - submx_rowsub
          - eqmx_rowsub_comp_perm
          - eqmx_rowsub_comp
          - eqmx_rowsub
          - col_mx_sub
          - addsmxE
          - addsmx_sub
          - addsmxSl
          - addsmxSr
          - addsmx_idPr
          - addsmx_idPl
          - adds0mx
          - addsmx0
          - addsmx_nop_eq0
          - addsmx_nop0
          - addsmx_nop_id
          - addsmxC
          - adds0mx_id
          - addsmx0_id
          - addsmxA
          - addsmxMr
          - addsmxS
          - addmx_sub_adds
          - addsmx_addKl
          - addsmx_addKr
          - adds_eqmx
          - genmx_adds
          - sub_addsmxP
          - genmx_sums
          - sumsmx_sup
          - sumsmx_subP
          - summx_sub_sums
          - sumsmxS
          - eqmx_sums
          - sub_sums_genmxP
          - sub_sumsmxP
          - sumsmxMr_gen
          - sumsmxMr
          - rank_pid_mx
          - rank_copid_mx
          - mxrank_compl
          - mxrank_ker
          - kermx_eq0
          - mxrank_coker
          - cokermx_eq0
          - mulmx_ker
          - mulmxKV_ker
          - sub_kermxP
          - sub_kermx
          - kermx0
          - mulmx_free_eq0
          - inj_row_free
          - row_freePn
          - negb_row_free
          - mulmx0_rank_max
          - mxrank_Frobenius
          - mxrank_mul_min
          - addsmx_compl_full
          - sub_capmx_gen
          - capmx_witnessP
          - capmx_normP
          - capmx_norm_eq
          - capmx_nopP
          - sub_qidmx
          - qidmx_cap
          - capmx_eq_norm
          - capmxE
          - capmxSl
          - sub_capmx
          - capmxC
          - capmxSr
          - capmx_idPr
          - capmx_idPl
          - capmxS
          - cap_eqmx
          - capmxMr
          - cap0mx
          - capmx0
          - capmxT
          - capTmx
          - capmx_nop_id
          - cap1mx
          - capmx1
          - genmx_cap
          - capmxA
          - bigcapmx_inf
          - sub_bigcapmxP
          - genmx_bigcap
          - matrix_modl
          - matrix_modr
          - capmx_compl
          - mxrank_mul_ker
          - mxrank_injP
          - mxrank_disjoint_sum
          - diffmxE
          - genmx_diff
          - diffmxSl
          - capmx_diff
          - addsmx_diff_cap_eq
          - mxrank_cap_compl
          - mxrank_sum_cap
          - mxrank_adds_leqif
          - rank_col_mx0
          - rank_col_0mx
          - rank_row_mx0
          - rank_row_0mx
          - rank_diag_block_mx
          - proj_mx_sub
          - proj_mx_compl_sub
          - proj_mx_id
          - proj_mx_0
          - add_proj_mx
          - proj_mx_proj
          - complete_unitmx
          - eqmxMunitP
          - eq_rank_unitmx
          - maxrowsub_free
          - eq_maxrowsub
          - maxrankfun_inj
          - maxrowsub_full
          - fullrowsub_full
          - fullrowsub_unit
          - fullrowsub_free
          - mxrank_fullrowsub
          - eq_fullrowsub
          - fullrankfun_inj
          - binary_mxsum_proof
          - nary_mxsum_proof
          - mxdirectP
          - mxdirect_trivial
          - mxrank_sum_leqif
          - mxdirectE
          - mxdirectEgeq
          - mxdirect_addsE
          - mxdirect_addsP
          - mxdirect_sums_recP
          - mxdirect_sumsP
          - mxdirect_sumsE
          - sub_daddsmx
          - sub_dsumsmx
          - eigenspaceP
          - eigenvalueP
          - eigenvectorP
          - mxdirect_sum_eigenspace
          - eqmx_stable
          - stablemx_row_base
          - stablemx_full
          - stablemxM
          - stablemxD
          - stablemxN
          - stablemxC
          - stablemx0
          - stableDmx
          - stableNmx
          - stable0mx
          - stableCmx
          - stablemx_sums
          - stablemx_unit
          - comm_mx_stable
          - comm_mx_stable_ker
          - comm_mx_stable_eigenspace
          - mxdirect_delta
          - card_GL
          - LUP_card_GL
          - card_GL_1
          - card_GL_2
          - logn_card_GL_p
          - mem0mx
          - memmx0
          - memmx1
          - memmx_subP
          - memmx_eqP
          - memmx_addsP
          - memmx_sumsP
          - has_non_scalar_mxP
          - genmx_muls
          - mem_mulsmx
          - mulsmx_subP
          - mulsmxS
          - muls_eqmx
          - mulsmxP
          - mulsmxA
          - mulsmxDl
          - mulsmxDr
          - mulsmx0
          - muls0mx
          - mxring_idP
          - cent_mx_fun_is_linear
          - cent_rowP
          - cent_mxP
          - scalar_mx_cent
          - center_mx_sub
          - center_mxP
          - mxring_id_uniq
          - cent_mx_ideal
          - cent_mx_ring
          - mxdirect_adds_center
          - mxdirect_sums_center
          - Gaussian_elimination_map
          - mxrank_map
          - row_free_map
          - row_full_map
          - map_row_ebase
          - map_col_ebase
          - map_row_base
          - map_col_base
          - map_pinvmx
          - map_kermx
          - map_cokermx
          - map_submx
          - map_ltmx
          - map_eqmx
          - map_genmx
          - map_addsmx
          - map_capmx_gen
          - map_capmx
          - map_complmx
          - map_diffmx
          - map_eigenspace
          - eigenvalue_map
          - memmx_map
          - map_mulsmx
          - map_cent_mx
          - map_center_mx
          - eqmx_col
          - rank_mxdiag
      - path: mathcomp/field/separable.v
        theorems:
          - separable_poly_neq0
          - poly_square_freeP
          - separable_polyP
          - separable_coprime
          - separable_nosquare
          - separable_deriv_eq0
          - dvdp_separable
          - separable_mul
          - eqp_separable
          - separable_root
          - separable_prod_XsubC
          - make_separable
          - separable_map
          - large_field_PET
          - char0_PET
          - Derivation_mul
          - Derivation_mul_poly
          - DerivationS
          - Derivation1
          - Derivation_scalar
          - Derivation_exp
          - Derivation_horner
          - separable_elementP
          - base_separable
          - separable_nz_der
          - separablePn
          - separable_root_der
          - Derivation_separable
          - extendDerivation_additive_subproof
          - extendDerivation_scalable_subproof
          - extendDerivation_id
          - extendDerivation_horner
          - extendDerivationP
          - Derivation_separableP
          - separable_elementS
          - adjoin_separableP
          - separable_exponent
          - charf0_separable
          - charf_p_separable
          - charf_n_separable
          - purely_inseparable_elementP
          - separable_inseparable_element
          - base_inseparable
          - sub_inseparable
          - cyclic_or_large
          - finite_PET
          - Primitive_Element_Theorem
          - adjoin_separable
          - strong_Primitive_Element_Theorem
          - separable_add
          - separable_sum
          - inseparable_add
          - inseparable_sum
          - separableP
          - purely_inseparableP
          - adjoin_separable_eq
          - separable_inseparable_decomposition
          - separable_generator_mem
          - separable_generatorP
          - separable_generator_maximal
          - sub_adjoin_separable_generator
          - eq_adjoin_separable_generator
          - separable_refl
          - separable_trans
          - separableS
          - separableSl
          - separableSr
          - separable_Fadjoin_seq
          - purely_inseparable_refl
          - purely_inseparable_trans