name: simple_lean_test
num_files: 1
language: LEAN4
few_shot_data_path_for_retrieval: null
few_shot_metadata_filename_for_retrieval: null
dfs_data_path_for_retrieval: null
dfs_metadata_filename_for_retrieval: local.meta.json
theorem_cnt: 1
timeout_per_theorem_in_secs: 720
datasets:
- project: <root>/data/proofs/lean/lean4_proj
  files:
  - path: Lean4Proj/Basic.lean
    theorems: "*"