training_data_dir: /mnt/sdd1/<user>/data/compcert/train/20240105-021649/
training_meta_filename: local.meta.json
training_data_log_dir: .log/run_training/logs/dataset_logs
training_dataset_type: CodeT5TrainingDataset
training_data_formatter_type: CodeT5PromptTrainingDataFormatter
training_dataset_args:
  characters_per_token: 3.6
  max_tokens: 2048
eval_data_dir: /mnt/sdd1/<user>/data/compcert/test/20240105-021512/
eval_meta_filename: local.meta.json
eval_data_log_dir: .log/run_training/logs/dataset_logs
test_data_dir: 
test_meta_filename: 
test_data_log_dir: 