training_data_dir: <root>/data/proofsteps/CompCert/20240510-053859/train/
training_meta_filename: local.meta.json
training_data_log_dir: <root>/data/proofsteps/training_results/logs/dataset_logs
training_dataset_type: CodeT5TrainingDataset
training_data_formatter_type: CodeT5PromptTrainingDataFormatter
training_dataset_args:
  characters_per_token: 3.6
  max_tokens: 2048
  no_steps: True
eval_data_dir: <root>/data/proofsteps/CompCert/20240510-053859/test
eval_meta_filename: local.meta.json
eval_data_log_dir: <root>/data/proofsteps/training_results/logs/dataset_logs
test_data_dir: 
test_meta_filename: 
test_data_log_dir: 