training_data_dir: .log/train
training_meta_filename: local.meta.json
training_data_log_dir: .log/run_training/logs/dataset_logs
training_dataset_type: TheoremProvingTrainingDataset
training_data_formatter_type: BasicTrainingDataFormatterCallback
training_dataset_args:   
eval_data_dir: 
eval_meta_filename: 
eval_data_log_dir: 
test_data_dir: 
test_meta_filename: 
test_data_log_dir: 